### ISSUE TITLE
crash in `server` on OpenBSD

### ISSUE THREAD

**Issue by ams** [LM-3/chaos#72]
```
(gdb) bt full
#0  clear (ptr=0xffffffffa2fb1501 <Address 0xffffffffa2fb1501 out of bounds>, n=104) at ../chncp/chutil.c:158
No locals.
#1  0x00000ac8c37152af in allconn () at ../chncp/chutil.c:47
	conn = (struct connection *) 0xffffffffa2fb1500
	cptr = (struct connection **) 0xac8c371f200
#2  0x00000ac8c3715cd1 in ch_listen (pkt=0xacbbc1b0000, rwsize=0) at ../chncp/chuser.c:93
	conn = (struct connection *) 0x9200000000
	pktl = (struct packet *) 0xacbbc1b0000
	opkt = (struct packet *) 0xac8c3713c71
#3  0x00000ac8c371798b in rcvrfc (pkt=0xacbbc1b0f00) at ../chncp/chrcv.c:511
	p = (struct packet *) 0xacbbc1b0000
	conn = (struct connection *) 0x0
	conptr = (struct connection **) 0xac8c371f2a0
	opkt = (struct packet **) 0xac8c371f2a8
	pktl = (struct packet *) 0x0
#4  0x00000ac8c3716aa0 in rcvpkt (xp=0xac8c371f0c8) at ../chncp/chrcv.c:101
	i = 2763
	pkt = (struct packet *) 0xacbbc1b0f00
	conn = (struct connection *) 0xacbbc1b0f00
	index = 2760
#5  0x00000ac8c371308d in ch_rcv_pkt_buffer (buffer=0xac8c371e000 "", size=28) at server.c:895
	pkt = (struct packet *) 0xacbbc1b0f00
	xp = (struct chxcvr *) 0x4
#6  0x00000ac8c3712ff4 in read_chaos () at server.c:748
	ret = 28
	len = 28
	id = 11866918926074
	lenbytes = 0x7f7ffffde9dc ""
	data = (u_char *) 0x1 <Address 0x1 out of bounds>
	resp = (u_char *) 0x7f7ffffdeaa0 "\003"
#7  0x00000ac8c3713356 in chaos_poll () at server.c:819
	ufds = 0x7f7ffffdeaa0
	ufds_type = 0x7f7ffffdea70
	ufds_conn_num = 0x7f7ffffdea40
	n = 1
	i = 0
	ret = 1
	timeout = 10
#8  0x00000ac8c371397b in main (argc=2, argv=0x7f7ffffdebc8) at server.c:986
	c = -1
	waiting = -1017766151
Current language:  auto; currently minimal
```

**Comment by ams** [comment]
Fixed.
