### ISSUE TITLE
crash when using local backend

### ISSUE THREAD

**Issue by ams** [LM-3/chaos#74]
```
(gdb) bt full
#0  0x000001eddea4adb3 in getwork () at chaos/cmd/FILE.c:718
	packet = (struct packet *) 0x30d97000
	t = (struct transaction *) 0x1f026964700
	c = (struct command *) 0x0
	cp = (unsigned char *) 0x0
	length = 0
	fhname = 0x1eddea39541 ""
	cname = 0x0
	save = 0 '\0'
	errcode = 12
	p = {cp_op = 0 '\0', cp_data = '\0' <repeats 487 times>}
#1  0x000001eddea4acc4 in _processdata (conn=0x1f0bd0ccf00) at chaos/cmd/FILE.c:603
	t = (struct transaction *) 0x0
#2  0x000001f0ddb8d831 in _rthread_start (v=Variable "v" is not available.
) at /usr/src/lib/librthread/rthread.c:96
	thread = Variable "thread" is not available.
(gdb) 
```

**Comment by ams** [comment]
Fixed.
